apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ldrnj5t42-java-springboot
  janus-idp.io/tekton: ldrnj5t42-java-springboot
  backstage.io/kubernetes-id: ldrnj5t42-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ldrnj5t42-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
